name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        docker build --tag lyubengeorgiev/devops-classwork-1:latest ./src/

    # - name: SonarCloud Scan

  
    # - name: Snyk Security Scan
    #   working-directory: ${{github.workspace}}/src
    #   run: |
    #     # Install Dependencies
    #     pip install -r requirements.txt

    #     # Install the Snyk CLI
    #     npm install -g snyk

    #     # Authenticate with Snyk using your API token or token from secrets
    #     snyk auth ${{ secrets.SNYK_AUTH_TOKEN }}

    #     # Run Snyk to scan your project
    #     snyk test
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}
      with:
        args: ${{github.workspace}}/src

    - name: Login to DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push to DockerHub
      run: |
        docker push lyubengeorgiev/devops-classwork-1:latest