name: Main CI

on:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: flake8 Lint
        uses: py-actions/flake8@v2

  editorconfig-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Get Editorconfig Checker
        uses: editorconfig-checker/action-editorconfig-checker@main
      - name: Run Editorconfig Checker
        working-directory: ${{github.workspace}}/src
        run: editorconfig-checker

      

  markdownlint-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: /*.md
          dot: true

  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependecies
        run: |
          pip3 install -r ./src/requirements.txt
          
      - name: Run Python Unit tests
        run: python3 -m unittest ./tests/app_test.py

  build:
    needs:
      ["lint", "markdownlint-cli", "markdownlint-cli", "gitleaks", "unit-tests"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Snyk Security Scan
      working-directory: ${{github.workspace}}/src
      run: |
        # Install Dependencies
        pip install -r requirements.txt

        # Install the Snyk CLI
        npm install -g snyk

        # Authenticate with Snyk using your API token or token from secrets
        snyk auth ${{ secrets.SNYK_AUTH_TOKEN }}

        # Run Snyk to scan your project
        snyk test

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build the Docker image
      run: |
        docker build --tag lyubengeorgiev/devops-classwork-1:latest .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'lyubengeorgiev/devops-classwork-1:latest'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'

    - name: Login to DockerHub
      run: |
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Push to DockerHub
      run: |
        docker push lyubengeorgiev/devops-classwork-1:latest